services:
    
  sonarqube:  
    image: sonarqube:latest
    container_name: db-sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"  
    ports:
      - "9000:9000"

  judge-dredd:
    build:
      context: /src/JudgeDredd
      dockerfile: Dockerfile
    container_name: dc-judgedredd
    ports:
      - "5005:8080"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: dc-postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: somew0rds
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dc-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: scoth@tiger.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: